netdev: Support for tap device
vmware/pmd pull request #20
Opened 2022-11-28 14:04 UTC by ntsbtz

1. Configure Tap device
2. Remove Tap device
3. Pmctl command line support to configure and remove Tap device 
4. CI test to configure Tap device

2022-11-28 14:08 UTC, ssahani requested changes

2023-01-24 10:20 UTC, tapakund approved these changes

2023-01-24 10:20 UTC, merged

2023-01-24 10:48 UTC, ssahani commented
The documentation is complete wrong . WHy it's changed to test99. Interface name never a `test99`. Please dont merge such unaddressed commmits

2023-01-25 13:35 UTC, tapakund commented
@ntsbtz can you please address the comments from @ssahani in follow up PR?

2023-01-25 14:58 UTC, ntsbtz commented
> @ntsbtz can you please address the comments from @ssahani in follow up PR?

Already addressed https://github.com/vmware/pmd/pull/21